In [36]:
import csv
from collections import OrderedDict
from datetime import datetime

class mylist(list):
    def __gt__(self, other):
        return [row_value > other for row_value in self]

l = mylist([1,23])

class DataFrame(object):

    @classmethod
    def from_csv(cls, file_path, delimiting_character=',', quote_character='"'):
        with open(file_path, 'rU') as infile:
            reader = csv.reader(infile, delimiter=delimiting_character, quotechar=quote_character)
            data = []

            for row in reader:
                data.append(row)

            return cls(list_of_lists=data)



    def __init__(self, list_of_lists, header=True):
        
        #A2-task 1
        def unique_values(g):
            s =set()
            for x in g:
                if x in s: 
                    return False
                s.add(x)
            return True
        
        if header:
            self.header = list_of_lists[0]
            #task 1
            if not unique_values(self.header):
                raise Exception('Error: Not Unique')
            
            self.data = list_of_lists[1:]
        else:
            self.data = list_of_lists
            self.header = ['column' + str(index + 1) for index, column in enumerate(self.data[0])]
        
        #A2-task2
        
        for row in self.data:
            tmp = []
            for s in row:
                if isinstance(s , str):
                    tmp.append(s.strip())
                else:
                    tmp.append(s)
            row[:] = tmp[:]


        self.data = [OrderedDict(zip(self.header, row)) for row in self.data]
    
    def __getitem__(self, item):
        # this is for rows only
        if isinstance(item, (int, slice)):
            return mylist(self.data[item])

        # this is for columns only
        elif isinstance(item, str):
            return mylist([row[item] for row in self.data])

        # this is for rows and columns
        elif isinstance(item, tuple):
            if isinstance(item[0], list) or isinstance(item[1], list):

                if isinstance(item[0], list):
                    rowz = [row for index, row in enumerate(self.data) if index in item[0]]
                else:
                    rowz = self.data[item[0]]

                if isinstance(item[1], list):
                    if all([isinstance(thing, int) for thing in item[1]]):
                        return mylist([[column_value for index, column_value in enumerate([value for value in row.values()]) if index in item[1]] for row in rowz])
                    elif all([isinstance(thing, str) for thing in item[1]]):
                        return mylist([[row[column_name] for column_name in item[1]] for row in rowz])
                    else:
                        raise TypeError('What the hell is this?')

                else:
                    return mylist([[value for value in row.items()][item[1]] for row in rowz])
            else:
                if isinstance(item[1],  slice) or isinstance(item[0], slice):
                    return mylist([[value for value in row.items()][item[1]] for row in self.data[item[0]]])
                
                elif isinstance(item[1], int):
                    return mylist([row for row in self.data[item[0]].items()][item[1]])
                
                
                elif isinstance(item[1], str):
                    return mylist(self[item[1]][item[0]])
                else:
                    raise TypeError('I don\'t know how to handle this...')

        # only for lists of column names A3-Task2
        elif isinstance(item, list):
            if isinstance(item[0], bool):
                if len(item) != len(self.data):
                    raise Exception("Slice length does not match data")
                else:
                    return mylist(self.data[i] for i in range(len(self.data)) if item[i])
            else:
                return mylist([[row[column_name] for column_name in item] for row in self.data])

        
     
        

        
    def get_rows_where_column_has_value(self, column_name, value, index_only=False):
        if index_only:
            return [index for index, row_value in enumerate(self[column_name]) if row_value==value]
        else:
            return [row for row in self.data if row[column_name]==value]

    #A2-task3
    def type_valid(self, column_name):
        from datetime import datetime
        if isinstance(self[column_name][0], (int, float, datetime)):
            return True
        else:
            return False
    
    def min(self, column_name):
        if not self.type_valid(column_name):
            raise Exception("Data Invalid Error")
        
        return min(self[column_name])
    
    def max(self, column_name):
        if not self.type_valid(column_name):
            raise Exception("Data Invalid Error")
        return max(self[column_name])
    
    def median(self, column_name):
        if not self.type_valid(column_name):
            raise Exception("Data Invalid Error")
        else:
            self[column_name].sort()
            lens = len(self[column_name])
            if lens%2 == 0:
                midl = lens/2
                res = self[column_name][int(midl)]
            else:
                odd = (lens /2)-1
                even = (lens /2)
                res = float(self[column_name][int(odd)] + self[column_name][int(even)]) / float(2)
        return res
    
    def mean(self, column_name):
        if not self.type_valid(column_name):
            raise Exception("Data Invalid Error")
        return float(sum(self[column_name])) / max(len(self[column_name]), 1)
    
    def _ss(self, column_name):
        #Return sum of square deviation of sequence data
        if not self.type_valid(column_name):
            raise Exception("Data Invalid Error")
        else:
            sum_value = 0
            mean_value =self.mean(column_name)
            for index, row_value in enumerate(self[column_name]):
                ss = (row_value-mean_value)**2
                sum_value += ss
            return ss
    
    def stdev(self, column_name):
        '''Calculate the population standard deviation'''
        n = len(self[column_name])
        ss = self._ss(column_name)
        svar = ss/n
        return svar**0.5
            
    
    
        
    #A2-task 4 add_rows                 
    def add_rows(self, list_of_lists):
        
        for l in list_of_lists:
            if len(l) != len(self.data[0]):
                raise Exception("The length of input does not match the column number")
                
        self.data = self.data + [OrderedDict(zip(self.header, row)) for row in list_of_lists] 
        
        
    #A2-task 5 add_column
    def add_column(self, list_of_values, column_name):
        if len(list_of_values) != len(self.data):
            raise Exception("The length of input does not match the column number")
        
        for row in self.data[::-1]:
            row[column_name] = list_of_values.pop()
            
    #assignment3 
    #A3-task1
    def sort_by(self, column_name, aescending):
        if aescending == True:
            return sorted(self[column_name])
        else:
            return sorted(self[column_name], reverse = True)

           
    #A3-task3
    def group_by(self, column_name1, column_name2, func):
    
        inputs = self[[column_name1,column_name2]]
        inputs_dict = dict()
        avgDict = dict()
        for each in inputs:
            if each[0] in inputs_dict:
                inputs_dict[each[0]].append(each[1])
            else:
                inputs_dict[each[0]] = [each[1]] 
        for k, v in inputs_dict.items():
            avgDict[k] = func(v)
        return avgDict
        
def avg(list_of_values):       
    return sum(list_of_values)/float(len(list_of_values))

    
infile = open('/Users/Lucinda/Desktop/660/data_source/SalesJan2009.csv')
lines = infile.readlines()
lines = [lines[i].strip('\n') for i in range(len(lines))]
data = [l.split(',') for l in lines]
things = lines[559].split('"')
data[559] = things[0].split(',')[:-1] +[things[1]] + things[-1].split(',')[1:]
data[559][2] = data[559][2].replace(',','')

for p in range(1, len(data)):
    data[p][2] = float(data[p][2])
    data[p][0] = datetime.strptime(data[p][0], '%m/%d/%y %H:%M')

    
    

df = DataFrame(list_of_lists=data)
# get the 5th row
fifth = df[4]
sliced = df[4:10]

# get item definition for df [row, column]

# get the third column
tupled = df[:, 2]
tupled_slices = df[0:5, :3]

tupled_bits = df[[1, 4], [1, 4]]


# adding header for data with no header
#df = DataFrame(list_of_lists=data[1:], header=False)

# fetch columns by name
# named = df['column1']
# named_multi = df[['column1', 'column7']]

# #fetch rows and (columns by name)
# named_rows_and_columns = df[:5, 'column7']
# named_rows_and_multi_columns = df[:5, ['column4', 'column7']]


#testing from_csv class method
# df = DataFrame.from_csv('/Users/Lucinda/Desktop/660/data_source/SalesJan2009.csv')
# rows = df.get_rows_where_column_has_value('Payment_Type', 'Visa')
# indices = df.get_rows_where_column_has_value('Payment_Type', 'Visa', index_only=True)

# rows_way2 = df[indices, ['Product', 'Country']]

In [37]:
df[df['Price'] > 1400]

[OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 4, 12, 56)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Visa'),
              ('Name', 'Gerd W'),
              ('City', 'Cahaba Heights'),
              ('State', 'AL'),
              ('Country', 'United States'),
              ('Account_Created', '11/15/08 15:47'),
              ('Last_Login', '1/4/09 12:45'),
              ('Latitude', '33.52056'),
              ('Longitude', '-86.8025')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 6, 7, 45)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Visa'),
              ('Name', 'Sabine'),
              ('City', 'London'),
              ('State', 'England'),
              ('Country', 'United Kingdom'),
              ('Account_Created', '1/6/09 7:00'),
              ('Last_Login', '1/6/09 9:17'),
              ('Latitude', '51.52721'),
              ('Longitude', '0.14559')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 5, 20, 0)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Visa'),
              ('Name', 'James'),
              ('City', 'Burpengary'),
              ('State', 'Queensland'),
              ('Country', 'Australia'),
              ('Account_Created', '12/10/08 19:53'),
              ('Last_Login', '1/8/09 17:58'),
              ('Latitude', '-27.1666667'),
              ('Longitude', '152.95')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 6, 22, 19)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Amex'),
              ('Name', 'Ritz'),
              ('City', 'Pittsfield'),
              ('State', 'VT'),
              ('Country', 'United States'),
              ('Account_Created', '1/6/09 12:00'),
              ('Last_Login', '1/9/09 10:05'),
              ('Latitude', '43.77222'),
              ('Longitude', '-72.81333')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 6, 23, 0)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Amex'),
              ('Name', 'Sylvia'),
              ('City', 'Pittsfield'),
              ('State', 'VT'),
              ('Country', 'United States'),
              ('Account_Created', '1/6/09 12:00'),
              ('Last_Login', '1/9/09 10:05'),
              ('Latitude', '43.77222'),
              ('Longitude', '-72.81333')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 7, 15, 12)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Visa'),
              ('Name', 'Anabela'),
              ('City', 'Flossmoor'),
              ('State', 'IL'),
              ('Country', 'United States'),
              ('Account_Created', '1/5/09 19:55'),
              ('Last_Login', '1/9/09 16:03'),
              ('Latitude', '41.54278'),
              ('Longitude', '-87.68472')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 3, 10, 11)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Visa'),
              ('Name', 'Christiane'),
              ('City', 'Delray Beach'),
              ('State', 'FL'),
              ('Country', 'United States'),
              ('Account_Created', '1/3/09 9:27'),
              ('Last_Login', '1/10/09 9:46'),
              ('Latitude', '26.46111'),
              ('Longitude', '-80.07306')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 4, 8, 39)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Diners'),
              ('Name', 'Baybars'),
              ('City', 'Prince Albert'),
              ('State', 'Saskatchewan'),
              ('Country', 'Canada'),
              ('Account_Created', '1/3/09 17:17'),
              ('Last_Login', '1/11/09 21:05'),
              ('Latitude', '53.2'),
              ('Longitude', '-105.75')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 7, 0, 12)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Mastercard'),
              ('Name', 'Deirdre'),
              ('City', 'Lausanne'),
              ('State', 'Vaud'),
              ('Country', 'Switzerland'),
              ('Account_Created', '12/1/08 6:25'),
              ('Last_Login', '1/12/09 6:55'),
              ('Latitude', '46.5333333'),
              ('Longitude', '6.6666667')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 12, 3, 3)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Mastercard'),
              ('Name', 'Valda'),
              ('City', 'Irvine'),
              ('State', 'CA'),
              ('Country', 'United States'),
              ('Account_Created', '1/12/09 2:48'),
              ('Last_Login', '1/14/09 1:07'),
              ('Latitude', '33.66944'),
              ('Longitude', '-117.82222')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 5, 8, 58)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Mastercard'),
              ('Name', 'Marcia'),
              ('City', 'Telgte'),
              ('State', 'Nordrhein-Westfalen'),
              ('Country', 'Germany'),
              ('Account_Created', '9/1/08 3:39'),
              ('Last_Login', '1/14/09 2:07'),
              ('Latitude', '52.3333333'),
              ('Longitude', '7.9')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 16, 7, 21)),
              ('Product', 'Product1'),
              ('Price', 2100.0),
              ('Payment_Type', 'Mastercard'),
              ('Name', 'Gerald'),
              ('City', 'Mahopac'),
              ('State', 'NY'),
              ('Country', 'United States'),
              ('Account_Created', '11/3/08 14:28'),
              ('Last_Login', '1/16/09 6:08'),
              ('Latitude', '41.37222'),
              ('Longitude', '-73.73389')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 18, 11, 34)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Visa'),
              ('Name', 'Cheryl'),
              ('City', 'New Malden'),
              ('State', 'England'),
              ('Country', 'United Kingdom'),
              ('Account_Created', '10/28/05 14:57'),
              ('Last_Login', '1/18/09 10:27'),
              ('Latitude', '51.4166667'),
              ('Longitude', '-0.25')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 18, 13, 26)),
              ('Product', 'Product3'),
              ('Price', 7500.0),
              ('Payment_Type', 'Mastercard'),
              ('Name', 'Julianne'),
              ('City', 'Navan'),
              ('State', 'Meath'),
              ('Country', 'Ireland'),
              ('Account_Created', '1/18/09 12:20'),
              ('Last_Login', '1/18/09 12:20'),
              ('Latitude', '53.6527778'),
              ('Longitude', '-6.6813889')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 18, 16, 32)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Visa'),
              ('Name', 'Therese'),
              ('City', 'Los Angeles'),
              ('State', 'CA'),
              ('Country', 'United States'),
              ('Account_Created', '1/18/09 16:23'),
              ('Last_Login', '1/18/09 16:54'),
              ('Latitude', '34.05222'),
              ('Longitude', '-118.24278')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 18, 17, 4)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Visa'),
              ('Name', 'Abdul-L'),
              ('City', 'New York'),
              ('State', 'NY'),
              ('Country', 'United States'),
              ('Account_Created', '1/18/09 16:58'),
              ('Last_Login', '1/18/09 16:58'),
              ('Latitude', '40.71417'),
              ('Longitude', '-74.00639')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 18, 17, 20)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Visa'),
              ('Name', 'heidi'),
              ('City', 'Saint Paul'),
              ('State', 'MN'),
              ('Country', 'United States'),
              ('Account_Created', '1/18/09 17:16'),
              ('Last_Login', '1/18/09 17:16'),
              ('Latitude', '44.94444'),
              ('Longitude', '-93.09306')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 18, 17, 39)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Visa'),
              ('Name', 'jiyoung'),
              ('City', 'New York'),
              ('State', 'NY'),
              ('Country', 'United States'),
              ('Account_Created', '1/18/09 17:34'),
              ('Last_Login', '1/18/09 17:34'),
              ('Latitude', '40.71417'),
              ('Longitude', '-74.00639')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 8, 11, 55)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Visa'),
              ('Name', 'Caren'),
              ('City', 'Braunschweig'),
              ('State', 'Lower Saxony'),
              ('Country', 'Germany'),
              ('Account_Created', '1/3/09 12:39'),
              ('Last_Login', '1/19/09 8:31'),
              ('Latitude', '52.2666667'),
              ('Longitude', '10.5333333')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 14, 5, 20)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Visa'),
              ('Name', 'Kristen'),
              ('City', 'Binningen'),
              ('State', 'Basel-Country'),
              ('Country', 'Switzerland'),
              ('Account_Created', '1/12/09 13:31'),
              ('Last_Login', '1/19/09 13:07'),
              ('Latitude', '47.5333333'),
              ('Longitude', '7.5666667')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 18, 13, 49)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Visa'),
              ('Name', 'Bev'),
              ('City', 'San Ramon'),
              ('State', 'CA'),
              ('Country', 'United States'),
              ('Account_Created', '1/11/09 12:00'),
              ('Last_Login', '1/19/09 18:07'),
              ('Latitude', '37.78'),
              ('Longitude', '-121.97694')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 20, 5, 24)),
              ('Product', 'Product3'),
              ('Price', 7500.0),
              ('Payment_Type', 'Mastercard'),
              ('Name', 'Amanda'),
              ('City', 'Shreveport'),
              ('State', 'LA'),
              ('Country', 'United States'),
              ('Account_Created', '1/20/09 5:13'),
              ('Last_Login', '1/20/09 7:15'),
              ('Latitude', '32.525'),
              ('Longitude', '-93.75')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 7, 6, 11)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Visa'),
              ('Name', 'Tiffany'),
              ('City', 'Paris'),
              ('State', 'Ile-de-France'),
              ('Country', 'France'),
              ('Account_Created', '1/7/09 5:30'),
              ('Last_Login', '1/20/09 11:22'),
              ('Latitude', '48.8666667'),
              ('Longitude', '2.3333333')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 10, 8, 33)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Mastercard'),
              ('Name', 'Patricia'),
              ('City', 'Portola Valley'),
              ('State', 'CA'),
              ('Country', 'United States'),
              ('Account_Created', '2/4/07 10:09'),
              ('Last_Login', '1/20/09 22:06'),
              ('Latitude', '37.38417'),
              ('Longitude', '-122.23417')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 16, 2, 41)),
              ('Product', 'Product3'),
              ('Price', 7500.0),
              ('Payment_Type', 'Visa'),
              ('Name', 'Kristyn'),
              ('City', 'Kearns'),
              ('State', 'UT'),
              ('Country', 'United States'),
              ('Account_Created', '1/15/09 18:01'),
              ('Last_Login', '1/21/09 1:02'),
              ('Latitude', '40.66'),
              ('Longitude', '-111.99556')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 6, 12, 45)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Amex'),
              ('Name', 'Kaylee'),
              ('City', 'Penngrove'),
              ('State', 'CA'),
              ('Country', 'United States'),
              ('Account_Created', '1/5/09 14:06'),
              ('Last_Login', '1/21/09 11:18'),
              ('Latitude', '38.29972'),
              ('Longitude', '-122.66556')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 11, 22, 22)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Visa'),
              ('Name', 'STEPHANIE'),
              ('City', 'Mona Vale'),
              ('State', 'New South Wales'),
              ('Country', 'Australia'),
              ('Account_Created', '12/30/08 17:48'),
              ('Last_Login', '1/21/09 22:33'),
              ('Latitude', '-33.6666667'),
              ('Longitude', '151.3')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 21, 12, 8)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Visa'),
              ('Name', 'Rosemary'),
              ('City', 'Jacksonville'),
              ('State', 'FL'),
              ('Country', 'United States'),
              ('Account_Created', '1/21/09 11:39'),
              ('Last_Login', '1/22/09 6:13'),
              ('Latitude', '30.33194'),
              ('Longitude', '-81.65583')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 3, 6, 41)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Visa'),
              ('Name', 'ayelet'),
              ('City', 'Malmo'),
              ('State', 'Skane'),
              ('Country', 'Sweden'),
              ('Account_Created', '8/7/08 9:24'),
              ('Last_Login', '1/22/09 11:24'),
              ('Latitude', '55.6'),
              ('Longitude', '13')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 1, 12, 20)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Visa'),
              ('Name', 'seemab'),
              ('City', 'San Pawl tat-Targa'),
              ('State', ''),
              ('Country', 'Malta'),
              ('Account_Created', '9/17/05 3:32'),
              ('Last_Login', '1/22/09 12:00'),
              ('Latitude', '35.9202778'),
              ('Longitude', '14.4425')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 4, 22, 0)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Amex'),
              ('Name', 'Lucien'),
              ('City', 'Wiesbaden'),
              ('State', 'Hessen'),
              ('Country', 'Germany'),
              ('Account_Created', '1/4/09 11:32'),
              ('Last_Login', '1/22/09 12:21'),
              ('Latitude', '50.0833333'),
              ('Longitude', '8.25')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 16, 1, 7)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Diners'),
              ('Name', 'Lesley'),
              ('City', 'Cork'),
              ('State', 'Cork'),
              ('Country', 'Ireland'),
              ('Account_Created', '1/14/09 4:10'),
              ('Last_Login', '1/22/09 15:06'),
              ('Latitude', '51.8986111'),
              ('Longitude', '-8.4958333')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 23, 3, 33)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Mastercard'),
              ('Name', 'Anja Langer'),
              ('City', 'Saint Paul'),
              ('State', 'MN'),
              ('Country', 'United States'),
              ('Account_Created', '1/23/09 3:00'),
              ('Last_Login', '1/23/09 3:00'),
              ('Latitude', '44.94444'),
              ('Longitude', '-93.09306')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 5, 2, 57)),
              ('Product', 'Product3'),
              ('Price', 7500.0),
              ('Payment_Type', 'Visa'),
              ('Name', 'Marion'),
              ('City', 'Rennes'),
              ('State', 'Brittany'),
              ('Country', 'France'),
              ('Account_Created', '12/29/08 3:16'),
              ('Last_Login', '1/23/09 7:29'),
              ('Latitude', '48.0833333'),
              ('Longitude', '-1.6833333')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 23, 7, 37)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Amex'),
              ('Name', 'Fatisha'),
              ('City', 'Miami'),
              ('State', 'FL'),
              ('Country', 'United States'),
              ('Account_Created', '1/23/09 6:32'),
              ('Last_Login', '1/24/09 6:54'),
              ('Latitude', '25.77389'),
              ('Longitude', '-80.19389')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 24, 9, 1)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Visa'),
              ('Name', 'Barbara'),
              ('City', 'Kirriemuir'),
              ('State', 'Scotland'),
              ('Country', 'United Kingdom'),
              ('Account_Created', '1/24/09 8:02'),
              ('Last_Login', '1/24/09 8:02'),
              ('Latitude', '56.6666667'),
              ('Longitude', '-3')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 11, 7, 10)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Visa'),
              ('Name', 'LAURIE'),
              ('City', 'Guildford'),
              ('State', 'England'),
              ('Country', 'United Kingdom'),
              ('Account_Created', '3/7/06 5:47'),
              ('Last_Login', '1/24/09 14:54'),
              ('Latitude', '51.2166667'),
              ('Longitude', '-0.5666667')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 7, 19, 3)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Mastercard'),
              ('Name', 'Cindy'),
              ('City', 'Englewood'),
              ('State', 'CO'),
              ('Country', 'United States'),
              ('Account_Created', '12/17/07 19:55'),
              ('Last_Login', '1/24/09 19:19'),
              ('Latitude', '39.64778'),
              ('Longitude', '-104.98722')]),
 OrderedDict([('Transaction_date', datetime.datetime(2009, 1, 6, 14, 38)),
              ('Product', 'Product2'),
              ('Price', 3600.0),
              ('Payment_Type', 'Mastercard'),
              ('Name', 'Elizabeth'),
              ('City', 'Den Haag'),
              ('State', 'Zuid-Holland'),

[False, True]

TypeError: unorderable types: list() > int()

In [38]:
df.group_by("Payment_Type", "Price", avg)

{'Amex': 1717.2727272727273,
 'Diners': 1503.370786516854,
 'Mastercard': 1655.0541516245487,
 'Visa': 1627.1072796934866}

In [74]:
type(df['Price'])

list

In [24]:
df[["Payment_Type", "Price"]]

[['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Amex', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 3600.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Diners', 1200.0],
 ['Mastercard', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Amex', 3600.0],
 ['Amex', 3600.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Amex', 1200.0],
 ['Visa', 3600.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Amex', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Diners', 3600.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 3600.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 3600.0],
 ['Mastercard', 3600.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 2100.0],
 ['Mastercard', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Mastercard', 7500.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 3600.0],
 ['Visa', 3600.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 7500.0],
 ['Mastercard', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Amex', 1200.0],
 ['Mastercard', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 7500.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Amex', 3600.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Diners', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Diners', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 3600.0],
 ['Amex', 3600.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Diners', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 3600.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 7500.0],
 ['Amex', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Mastercard', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 3600.0],
 ['Mastercard', 1200.0],
 ['Diners', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 3600.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Amex', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 3600.0],
 ['Visa', 3600.0],
 ['Mastercard', 1200.0],
 ['Amex', 1200.0],
 ['Amex', 800.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 3600.0],
 ['Diners', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 3600.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Diners', 1200.0],
 ['Diners', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Diners', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 3600.0],
 ['Mastercard', 1200.0],
 ['Amex', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 3600.0],
 ['Mastercard', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 3600.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Amex', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1250.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 3600.0],
 ['Mastercard', 3600.0],
 ['Amex', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Diners', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Amex', 3600.0],
 ['Visa', 1200.0],
 ['Mastercard', 7500.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 3600.0],
 ['Amex', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Amex', 3600.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Amex', 1200.0],
 ['Amex', 3600.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 3600.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 250.0],
 ['Visa', 3600.0],
 ['Visa', 3600.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Diners', 1200.0],
 ['Amex', 1200.0],
 ['Amex', 1800.0],
 ['Amex', 1200.0],
 ['Visa', 7500.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 7500.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 7500.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Diners', 1200.0],
 ['Mastercard', 1200.0],
 ['Amex', 3600.0],
 ['Mastercard', 1200.0],
 ['Diners', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Mastercard', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 3600.0],
 ['Mastercard', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 7500.0],
 ['Amex', 1200.0],
 ['Visa', 3600.0],
 ['Amex', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 13000.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 3600.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 3600.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Mastercard', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Amex', 3600.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 3600.0],
 ['Visa', 3600.0],
 ['Mastercard', 3600.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Diners', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 3600.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 3600.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Mastercard', 1200.0],
 ['Amex', 3600.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 3600.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 3600.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Mastercard', 3600.0],
 ['Visa', 3600.0],
 ['Diners', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 3600.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 3600.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 3600.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Mastercard', 3600.0],
 ['Amex', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 7500.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Mastercard', 3600.0],
 ['Mastercard', 3600.0],
 ['Amex', 1200.0],
 ['Visa', 3600.0],
 ['Mastercard', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 3600.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 3600.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Mastercard', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Mastercard', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 3600.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 3600.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Amex', 1200.0],
 ['Amex', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 3600.0],
 ['Diners', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 3600.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 3600.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Amex', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 7500.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Mastercard', 1200.0],
 ['Amex', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Diners', 3600.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 3600.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 7500.0],
 ['Diners', 7500.0],
 ['Diners', 1200.0],
 ['Amex', 1200.0],
 ['Amex', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 3600.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Amex', 1200.0],
 ['Mastercard', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 3600.0],
 ['Mastercard', 3600.0],
 ['Mastercard', 1200.0],
 ['Visa', 3600.0],
 ['Visa', 1200.0],
 ['Amex', 3600.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Mastercard', 1200.0],
 ['Visa', 1200.0],
 ['Visa', 1200.0],
 ['Diners', 1200.0],
 ['Mastercard', 3600.0],
 ['Visa', 1200.0],

In [1]:
#df.sort_by('Price', aescending = False)

In [74]:
print('max price:',df.max('Price'))
print('min price:',df.min('Price'))
print('mean price:',df.mean('Price'))
print('max date:',df.max('Transaction_date'))
print('min date:',df.min('Transaction_date'))
#print('mean date:',df.mean('Transaction_date'))
print('exception', df.max('Payment_Type'))

max price: 13000.0
min price: 250.0
mean price: 1633.7675350701402
max date: 2009-01-31 23:09:00
min date: 2009-01-01 01:26:00

Exception: Data Invalid Error

In [278]:
infile = open('/Users/Lucinda/Desktop/660/data_source/SalesJan2009.csv')
lines = infile.readlines()
lines = [lines[i].strip('\n') for i in range(len(lines))]
data = [l.split(',') for l in lines]
lines[559]

'1/28/09 18:00,Product1,"13,000",Visa,sandhya,Centennial                  ,CO,United States,12/2/06 23:24,2/7/09 15:18,39.57917,-104.87639'

In [201]:
new_rows = [[datetime(2011, 1, 28, 18, 0),
             'Product1',
              33000,
             'Visa',
             'sandhya',
             'Centennial',
             'CO',
             'United States',
             '12/2/06 23:24',
             '2/7/09 15:18',
             '39.57917',
             '-104.87639'],

             [datetime(2013, 1, 28, 18, 0),
             'Product1',
              36000,
             'Visa',
             'sandhya',
             'Centennial',
             'CO',
             'United States',
             '12/2/06 23:24',
             '2/7/09 15:18',
             '39.57917',
             '-104.87639'],
]
df.add_rows(new_rows)
df[-1]

OrderedDict([('Transaction_date', datetime.datetime(2013, 1, 28, 18, 0)),
             ('Product', 'Product1'),
             ('Price', 36000),
             ('Payment_Type', 'Visa'),
             ('Name', 'sandhya'),
             ('City', 'Centennial'),
             ('State', 'CO'),
             ('Country', 'United States'),
             ('Account_Created', '12/2/06 23:24'),
             ('Last_Login', '2/7/09 15:18'),
             ('Latitude', '39.57917'),
             ('Longitude', '-104.87639')])

In [332]:
new_column = list(range(len(df.data)))
df.add_column(new_column, 'new_column')

In [7]:
import itertools, operator

l = [{'dept':1, 'age':10, 'name':'Sam'},
        {'dept':1, 'age':12, 'name':'John'},
        {'dept':2,'age':20, 'name':'Mary'},
        {'dept':2,'age':11, 'name':'Mark'},
        {'dept':2,'age':11, 'name':'Tom'}]

groups = ['dept', 'age', 'name'] 

groups.reverse()
def hierachical_data(data, groups):
    g = groups[-1]
    g_list = []
    for key, items in itertools.groupby(data, operator.itemgetter(g)):
        g_list.append({key:list(items)})
    groups = groups[0:-1]
    if(len(groups) != 0):
        for e in g_list:
            for k,v in e.items():
                e[k] = hierachical_data(v, groups)

    return g_list

print (hierachical_data(l, groups))

[{1: [{10: [{'Sam': [{'dept': 1, 'name': 'Sam', 'age': 10}]}]}, {12: [{'John': [{'dept': 1, 'name': 'John', 'age': 12}]}]}]}, {2: [{20: [{'Mary': [{'dept': 2, 'name': 'Mary', 'age': 20}]}]}, {11: [{'Mark': [{'dept': 2, 'name': 'Mark', 'age': 11}]}, {'Tom': [{'dept': 2, 'name': 'Tom', 'age': 11}]}]}]}]

In [ ]:
[('Transaction_date', datetime.datetime(2013, 1, 28, 18, 0)),
             ('Product', 'Product1'),
             ('Price', 36000),
             ('Payment_Type', 'Visa'),
             ('Name', 'sandhya'),
             ('City', 'Centennial'),
             ('State', 'CO'),
             ('Country', 'United States'),
             ('Account_Created', '12/2/06 23:24'),
             ('Last_Login', '2/7/09 15:18'),
             ('Latitude', '39.57917'),
             ('Longitude', '-104.87639')]

In [13]:
solution1()

{'pipo': [{'a': 'pipo', 'b': 'titi'}, {'a': 'pipo', 'b': 'toto'}],
 'tata': [{'a': 'tata', 'b': 'foo'}, {'a': 'tata', 'b': 'bar'}]}

In [24]:
import math
class Circle(object):
    def __init__(self, x=0, y=0, r=0):
        self.x = x
        self.y = y
        self.r = r
    def __str__(self):
        return "Circle at (%d , %d). Radius: %f" % (self.x, self.y, self.r)
    def calcArea(self, r):
        self.r = r
        return (math.pi)*(r**2)
    def __gt__(self, circ1Radius, circ2Radius):
        self.circ1Radius = circ1Radius
        self.circ2Radius = circ2Radius
        r1 = circ1Radius
        r2 = circ2Radius
        return r1 > r2 #or r2 > r1
    #def __ge__(self, circ1Radius, circ2Radius)
    #And so on for __lt__(), __le__(), __ne__(), etc
B = Circle(1,2,5.0)
C = Circle(5,7,7)

In [25]:
B>C

TypeError: __gt__() missing 1 required positional argument: 'circ2Radius'